# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

"https://{default}/":
    type: upstream
    upstream: "app:http"
    cache:
      enabled: true

      # Base the cache on the session cookie and custom Drupal cookies. Ignore all other cookies.
      cookies: ['/^SS?ESS/', '/^Drupal.visitor/']

    redirects:
      expires: 1d
      paths:
        '/files/drupalcon-prague-2022-photobooth.zip':
          to: 'https://{default}/sites/default/files/DrupalConPrague2022-photobooth.zip'

"https://www.{default}/":
    type: redirect
    to: "https://{default}/"
